<!-- generated by looplan CreatePkg -->
<template>
    <div class="looplan-test1-test1">
        {{ viewValue || 'Test1' }}
    </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import type { Test1Props, Test1Emits } from '../types'

const props = withDefaults(defineProps<Test1Props>(), {
    modelValue: '',
})

const emit = defineEmits<Test1Emits>()

const viewValue = computed({
    get() {
        return props.modelValue
    },
    set(value: string) {
        emit('update:modelValue', value)
    },
})
</script>

<style scoped>
.looplan-test1-test1 {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    min-height: 36px;
    min-width: 120px;
    padding: 0 12px;
    border-radius: 8px;
    border: 1px solid #d9e0ee;
    color: #2b3447;
    background: #f7f9fd;
}
</style>
