<!-- generated by looplan CreatePkg -->
<template>
    <div class="testcurd-testcurd flex">
        <div class="commands">
            <div class="command" v-for="item in state.commands" :key="item.name"
                @click="onCommand(item.name, item.args)">{{
                    item.title }}</div>
        </div>
        <div ref="responseRef" class="response">
            <button @click="clearResponse">clear</button>
            <!-- 响应内容, 用markdown文档渲染 -->
            <div class="response-content">
                <DocView :content="state.response" />
            </div>
        </div>
    </div>
</template>

<script setup lang="ts">
import { nextTick, reactive, useTemplateRef } from 'vue'
import { useModelSpace } from 'looplan';
import { DocView } from 'looplan-doc'
const responseRef = useTemplateRef<HTMLDivElement>('responseRef');

const dataSpace = useModelSpace('data');
let TestTableModel = dataSpace.useModel('model/lm_test_table');

interface CommandItem {
    name: string;
    title: string;
    args?: any[];
}

const state = reactive({
    commands: <CommandItem[]>[
        {
            name: 'list',
            title: 'list'
        },
        {
            name: 'add',
            title: 'add',
            args: [
                {
                    name: 'test_add',
                },
            ],
        },
        {
            name: 'row',
            title: 'row(id=1)',
            args: [1],
        },
        {
            name: 'update',
            title: 'update(id=1)',
            args: [
                {
                    name: 'test_update',
                },
                1,
            ],
        },
        {
            name: 'save',
            title: 'save(data,id=1)',
            args: [
                {
                    name: 'test_save',
                },
                1,
            ],
        },
        {
            name: 'saveField',
            title: 'saveField(id=1,name)',
            args: [1, 'name', 'test_save_field'],
        },
        {
            name: 'count',
            title: 'count()',
            args: [],
        },
        {
            name: 'exists',
            title: 'exists()',
            args: [],
        },
        {
            name: 'paginate',
            title: 'paginate(1,10)',
            args: [1, 10, {}],
        },
        {
            name: 'paginateX',
            title: 'paginateX(0)',
            args: [0, { psize: 10 }, {}],
        },
        {
            name: 'saveOptions',
            title: 'saveOptions()',
            args: [[{ name: 'opt_1' }, { name: 'opt_2' }], {}, {}],
        },
        {
            name: 'multiSave',
            title: 'multiSave()',
            args: [[{ name: 'multi_1' }, { name: 'multi_2' }]],
        },
        {
            name: 'multiDelete',
            title: 'multiDelete([1,2])',
            args: [[1, 2], {}],
        },
        {
            name: 'delete',
            title: 'delete(id=1)',
            args: [1],
        },
        {
            name: 'restore',
            title: 'restore(id=1)',
            args: [1],
        },
    ],
    response: `

# list
\`\`\`json

[
    {
        id: 1,
        name: 'test1'
    },
    {
        id: 2,
        name: 'test2'
    }
]

\`\`\`
    `
})


const onCommand = async (name: string, args: any[] = []) => {
    console.log('onCommand', name, args);
    try {
        // @ts-ignore
        const method = TestTableModel[name];
        if (typeof method !== 'function') {
            throw new Error(`ModelClient.${name} is not a function`);
        }
        const res = await method.apply(TestTableModel, args);
        // const res = await TestTableModel[name]();
        console.log('res', res);

        state.response += `
# ${name}
args:
\`\`\`json
${JSON.stringify(args, null, 2)}
\`\`\`
result:
\`\`\`json
${JSON.stringify(res, null, 2)}
\`\`\`
`
    } catch (error: any) {

        console.log('error', error);
        state.response += `
# ${name} (error)
\`\`\`json
${JSON.stringify({
            args,
            message: error?.message || String(error),
        }, null, 2)}
\`\`\`
`
    }
    nextTick(() => {
        const el = responseRef.value;
        if (el) {
            el.scrollTop = el.scrollHeight;
        }
    });
}
const clearResponse = () => {
    state.response = '';
}

</script>

<style lang="scss" scoped>
.testcurd-testcurd {
    display: flex;

    .commands {
        width: 200px;
        height: 500px;
        background: #f5f7fa;
    }

    .response {
        flex: 1;
        margin-left: 16px;

        .response-content {
            height: 600px;
            overflow-y: auto;
            padding: 16px;
        }
    }




}
</style>
