<!-- generated by looplan CreatePkg -->
<template>
    <div class="lptest1-lptest1">
        <lp-component is="LpModelRender@Table" 
            :columns="columns" 
            :form="form"
            model="data@model/lm_test_table" ></lp-component>
    </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import type { LpTest1Props, LpTest1Emits } from '../types'


// 表格字段
const columns: any[] = [
    {
        title: 'ID',
        name: 'id',
        width: 80,
    },
    {
        title: '名称',
        name: 'name',
        width: 150,
    },
    {
        title: '年龄',
        name: 'age',
        width: 80,
    },
    {
        title: '金额',
        name: 'money',
        width: 100,
    },
    {
        title: '图片',
        name: 'img',
        width: 100,
        component: 'img',
    },
    {
        title: '内容',
        name: 'content',
    },
    {
        title: '创建时间',
        name: 'createdAt',
        width: 180,
    },
];

const form: any = {
    items: [
        {
            title: '名称',
            name: 'name',
            required: true,
            component: 'LpInput',
            componentProps: {
                placeholder: '请输入名称'
            }
        },
        {
            title: '年龄',
            name: 'age',
            component: 'LpInputNumber',
            componentProps: {
                placeholder: '请输入年龄'
            }
        },
        {
            title: '金额',
            name: 'money',
            component: 'LpInputNumber',
            componentProps: {
                placeholder: '请输入金额',
                precision: 2
            }
        },
        {
            title: '图片',
            name: 'img',
            component: 'lp-upload',
            componentProps: {
                type: 'img',
                limit: 1
            }
        },
        {
            title: '内容',
            name: 'content',
            component: 'LpInput',
            componentProps: {
                type: 'textarea',
                rows: 3,
                placeholder: '请输入内容'
            }
        }
    ]
};

</script>

<style lang="scss"></style>
