<!-- generated by looplan CreatePkg -->
<template>
    <div class="xxx-xxx">
        {{ viewValue || 'Xxx' }}
    </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import type { XxxProps, XxxEmits } from '../types'

const props = withDefaults(defineProps<XxxProps>(), {
    modelValue: '',
})

const emit = defineEmits<XxxEmits>()

const viewValue = computed({
    get() {
        return props.modelValue
    },
    set(value: string) {
        emit('update:modelValue', value)
    },
})
</script>

<style scoped>
.xxx-xxx {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    min-height: 36px;
    min-width: 120px;
    padding: 0 12px;
    border-radius: 8px;
    border: 1px solid #d9e0ee;
    color: #2b3447;
    background: #f7f9fd;
}
</style>
