export interface CreatePkgTemplateContext {
    pkgName: string;
    pkgTitle: string;
    componentName: string;
    componentTag: string;
}

export interface CreatePkgTemplateItem {
    fileName: string;
    relativePath: string;
    templatePath: string;
    outputRoot?: 'package' | 'project';
    transform?: (content: string, ctx: CreatePkgTemplateContext) => string;
}

const withGenMarkTs = (content: string) => `// generated by looplan CreatePkg\n${content}`;
const withGenMarkVue = (content: string) => `<!-- generated by looplan CreatePkg -->\n${content}`;
const withGenMarkMd = (content: string) => `<!-- generated by looplan CreatePkg -->\n${content}`;
const withGenMarkJson = (content: string) => `{\n  "_generatedBy": "looplan CreatePkg",\n${content.trim().slice(1)}`;

export const createPkgTemplateConfig: CreatePkgTemplateItem[] = [
    {
        fileName: 'config.ts',
        relativePath: '',
        templatePath: 'pkg/config.ts.tpl',
        transform: withGenMarkTs,
    },
    {
        fileName: 'package.json',
        relativePath: '',
        templatePath: 'pkg/package.json.tpl',
        transform: withGenMarkJson,
    },
    {
        fileName: 'index.ts',
        relativePath: 'src',
        templatePath: 'pkg/src/index.ts.tpl',
        transform: withGenMarkTs,
    },
    {
        fileName: 'types.ts',
        relativePath: 'src',
        templatePath: 'pkg/src/types.ts.tpl',
        transform: withGenMarkTs,
    },
    {
        fileName: '__COMPONENT_NAME__.vue',
        relativePath: 'src/components',
        templatePath: 'pkg/src/components/Component.vue.tpl',
        transform: withGenMarkVue,
    },
    {
        fileName: 'README.md',
        relativePath: 'public/docs/__PKG_NAME__',
        templatePath: 'docs/README.md.tpl',
        outputRoot: 'project',
        transform: withGenMarkMd,
    },
    {
        fileName: 'doc.config.json',
        relativePath: 'public/docs/__PKG_NAME__',
        templatePath: 'docs/doc.config.json.tpl',
        outputRoot: 'project',
        transform: withGenMarkJson,
    },
    {
        fileName: 'quick-start.md',
        relativePath: 'public/docs/__PKG_NAME__/guide',
        templatePath: 'docs/guide/quick-start.md.tpl',
        outputRoot: 'project',
        transform: withGenMarkMd,
    },
    {
        fileName: '__COMPONENT_NAME__.md',
        relativePath: 'public/docs/__PKG_NAME__/components',
        templatePath: 'docs/components/component.md.tpl',
        outputRoot: 'project',
        transform: withGenMarkMd,
    },
];
